// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDauamUXyMnOOtVCoi56IJxbgnX77tfrv0',
    appId: '1:33638021256:web:fe068a03a40aa4f629c73d',
    messagingSenderId: '33638021256',
    projectId: 'megas-1110a',
    authDomain: 'megas-1110a.firebaseapp.com',
    storageBucket: 'megas-1110a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhcpET-IF4_E7pl6aRBkGr96yXjDPcRmY',
    appId: '1:33638021256:android:70edc62951f2913b29c73d',
    messagingSenderId: '33638021256',
    projectId: 'megas-1110a',
    storageBucket: 'megas-1110a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi25yoxMYfu7MRC3RS7I0a35x4Ixq-74o',
    appId: '1:33638021256:ios:74e5c3be3688360c29c73d',
    messagingSenderId: '33638021256',
    projectId: 'megas-1110a',
    storageBucket: 'megas-1110a.appspot.com',
    iosClientId: '33638021256-q5ultneoa8mcgn6kph97japjgqds8jlr.apps.googleusercontent.com',
    iosBundleId: 'com.example.megas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi25yoxMYfu7MRC3RS7I0a35x4Ixq-74o',
    appId: '1:33638021256:ios:74e5c3be3688360c29c73d',
    messagingSenderId: '33638021256',
    projectId: 'megas-1110a',
    storageBucket: 'megas-1110a.appspot.com',
    iosClientId: '33638021256-q5ultneoa8mcgn6kph97japjgqds8jlr.apps.googleusercontent.com',
    iosBundleId: 'com.example.megas',
  );
}
